### ISSUE TITLE
Suggestion: ERC721 support

### ISSUE THREAD

**Issue by Rhovian** [animocabrands/ethereum-contracts-nft_staking#14]
It would be amazing to create a version of this staking contract that is ERC721 compatible.

I am going to be working on this myself as I need it for a project, but I would like to open a discussion and see if this has already been discussed among the devs; if there are any pitfalls there, etc.

**Comment by johnbisc** [comment]
Hi Mjavala, do you have any updates?
I also wrote my own contract, I would like your point of view? and compare both contracts

**Comment by Rhovian** [comment]
Hey, I wrote my own contract as well.

Mine essentially supports a pot that is distributed among NFT's.

Happy to talk and share, shoot me your discord @johnbisc

**Comment by johnbisc** [comment]
Look for @LAx#6189 on discord

**Comment by danduma** [comment]
Let me +1 this :)

@Mjavala I would be interested in this too! Mintermäl#4268 on discord

**Comment by Rhovian** [comment]
@johnbisc @ikutoski added you both.

Admittedly, my version could use some polish, but it's been thoroughly tested and audited (once, then did changes again)

**Comment by johnbisc** [comment]
> @johnbisc @ikutoski added you both.
> 
> Admittedly, my version could use some polish, but it's been thoroughly tested and audited (once, then did changes again)
where?

**Comment by nataouze** [comment]
Support for ERC721 is pretty straightforward: inherit from `ERC721Receiver` and implement the `onERC721Received` function as follow:

```solidity
    function onERC721Received(
        address, /*operator*/
        address from,
        uint256 tokenId,
        bytes calldata /*data*/
    ) external virtual override returns (bytes4) {
        require(address(whitelistedNftContract) == _msgSender(), "NftStaking: contract not whitelisted");
        _stakeNft(tokenId, from);
        return _ERC721_RECEIVED;
    }
```

This repo is currently not actively maintained so feel free to fork it.
